### ISSUE TITLE
Complete list of onshore wind units?

### ISSUE THREAD

**Issue by BenPortner** [MichaelKavanagh/elexon#5] opened 2020-07-06 08:00 UTC
Hi @MichaelKavanagh,

this is more of a data issue but maybe you know a solution: Is there a *complete* list of onshore wind units and their IDs somewhere? When downloading B1610 data, the PSR Type column says “Generation” for all entries and does not differentiate between wind / solar / gas / coal... When looking at B1420 data, I see several “Wind Onshore” units but the list is incomplete. Some units (e.g. BRYBW-1 and CRGHW-1) are classified again as “Generation”. A complete listing of onshore wind units would be very helpful. Do you know if it is available in any of the APIs?

Cheers
Ben

**Comment by michaelkavanagh** [comment] 2020-07-06 16:47
Yeah, I've battled with this before but didn't find a satisfactory answer. Please do update me if you find one.

**Comment by BogdanOxera** [comment] 2020-09-24 10:11
What I have used was https://www.netareports.com/data/elexon/ft.jsp?id=42 (this one is for wind, but you can do it for the other fuel types also) - the data from NETA -, then extract the Unit ID (the one between brackets) and then do a matching for the units mentioned as "Generation". I used VLOOKUP in Excel, but you can use whatever you prefer.

**Comment by BenPortner** [comment] 2020-09-25 20:32
@BogdanOxera that site is gold! Thanks for the tip!

**Comment by michaelkavanagh** [comment] 2020-09-26 11:24
My understanding is that NETA just aggregates and displays information from Elexon, is this correct?

A list of BM Units and fuel types is available from Elexon: B1420 (https://www.bmreports.com/bmrs/?q=foregeneration/capacityperunit), with more information about specific units available in other reports. However, the PSR type is not always correct, as noted above.

I am going to close this issue as it is not a bug in this package, but feel free to keep the discussion open.

**Closed as completed by michaelkavanagh** 2020-09-26 11:24 UTC

**Comment by BenPortner** [comment] 2020-09-26 13:27
@MichaelKavanagh NETA seems to use additional sources besides Elexon. From their website: 

> Welcome to the NETA reports website. This service provides access to data and information on the GB electricity market utilising Elexon market data as well as data from additional sources such as APX, LEBA, Meteo Group and Spectron. 

They got the PSR types of BRYBW-1 and CRGHW-1 correct, while Elexon doesn't. Thumbs up from my side!
